[build]
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "./paselista"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
