name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        # Actualizamos de '1.20' a '1.22'
        go-version: '1.22'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
